### ISSUE TITLE
[Bug Report] Airpods detection is not stable which sometimes pauses the music playback when "ear detection" is enabled

### ISSUE THREAD

**Issue by luoluomeng** [SpriteOvO/AirPodsDesktop#3]
## :bug: **Describe the bug**
Airpods detection is not stable which sometimes pauses the music playback when "ear detection" is enabled

## :scroll: **To Reproduce**
1. Pair AirPods pro
2. Start AirPodsDesktop
3. Start NeteaseCloudMusic and play some music
4. Listen to the music
5. Music pauses sometimes
6. Check the AirPodsDesktop immediately, the following status will show randomly:
- AirPods2 with incorrect battery status
- AirPods Pro but the battery status is incorrect(Such as Left:100%, right:30% but actually it's 30% 30%)
- Disconnected

## :rocket: **Expected behavior**
Music should continue playing and AirPodsDesktop should show the right status of AirPods pro

## :framed_picture: **Screenshots**
![image](https://user-images.githubusercontent.com/1762324/122169344-e1edf880-ceaf-11eb-9bda-2017b811b74e.png)
![image](https://user-images.githubusercontent.com/1762324/122169771-5aed5000-ceb0-11eb-8e7c-3c3d593e9aa6.png)
![image](https://user-images.githubusercontent.com/1762324/122169892-88d29480-ceb0-11eb-8e9b-96a249ed17fb.png)

## :gear: **Environments:** 
 - OS: Windows 10 21H1 build 19043
 - Version: 0.1.0

**Comment by SpriteOvO** [comment]
@luoluomeng Thanks for reporting!

> Music pauses sometimes

Yes, this is a known bug and I will try to fix it later.

> AirPods2 with incorrect battery status

The battery values of AirPods 2 looks good, what's wrong with that?

> AirPods Pro but the battery status is incorrect(Such as Left:100%, right:30% but actually it's 30% 30%)

Could you run `AirPodsDesktop` with the `--trace` argument, send the log file after a few seconds of running and write in the reply the value of the AirPods battery you see on your Apple device?

> Disconnected

Does the disconnection happen randomly? If it happens after putting the AirPods back in the case, this is expected behavior because the AirPods will stop working with the Bluetooth module after that.

**Comment by SpriteOvO** [comment]
Also I noticed something wrong with the font, it could be that the DPI needs some handling, can you tell me your Display Scale value?

**Comment by SpriteOvO** [comment]
My screen fits 100% DPI, so I'm not sure if the title text (e.g. "AirPods 2", "Disconnected") size is appropriate for high DPI users? If so, I will make the window size vary with DPI, otherwise I will make the font size as fixed as the window.

**Comment by luoluomeng** [comment]
@SpriteOvO Thanks, I'll try the trace mode and get some logs, For the issues mentioned above(recognized as airpods2, disconnected, or incorrect battery percentage), I think there should be some incorrect data in the broadcast, maybe we need to filter the correct one.

My screen is 3840x2160 with 250% DPI, the title looks good but as the screenshot shows, there are some truncations on the battery percentage number.

**Comment by luoluomeng** [comment]
[AirPodsDesktop.log](https://github.com/SpriteOvO/AirPodsDesktop/files/6666654/AirPodsDesktop.log)
Please check the log.
I also tried another similar project Winpods which has a similar issue, attach its log as well and hope it helps:
![image](https://user-images.githubusercontent.com/1762324/122315328-6726eb00-cf4c-11eb-995b-96f8b05fe4c3.png)

**Comment by SpriteOvO** [comment]
Hey, sorry it's a little late, I've pushed a few commits that should fix the problem, could you please test it ([artifact](https://github.com/SpriteOvO/AirPodsDesktop/runs/2930430469))? Thank you!

**Comment by luoluomeng** [comment]
> Hey, sorry it's a little late, I've pushed a few commits that should fix the problem, could you please test it ([artifact](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/978496952))? Thank you!

Of course!

**Comment by SpriteOvO** [comment]
@luoluomeng Any updates? I think this issue can be closed?

**Comment by luoluomeng** [comment]
Still observing, it's working well for 90% of the time, but it still has a chance to show the battery status when the AirPods is disconnected for a while:
![image](https://user-images.githubusercontent.com/1762324/124688996-4e39a600-df0a-11eb-8042-f0d4dda36b56.png)

**Comment by SpriteOvO** [comment]
@luoluomeng It may be helpful to post trace logs from around the time of the problem (about 3 minutes). :)

**Comment by SpriteOvO** [comment]
So, if your AirPods are actually closed (2 pods are in the box and the lid is closed), the InfoWindow pop-up may be because someone near you is also using AirPods.

This may not be completely fixable, as we have no way to track AirPods reliably for Apple's privacy reasons (MAC addresses are Random Non-resolvable).

A workaround for this is to reduce the receiving range, which can ignore the advertisement data packets broadcasted far away from your Bluetooth receiver. You can adjust this value in Settings in the tray right-click menu.

**Comment by luoluomeng** [comment]
Hmmm, adjust the range works, thanks!
